name: grade
on: [push]
jobs:
  run-using-github:
# see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context for defined variables
    if: github.repository_owner == 'cu-csci-2400-computer-systems'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: No bomb to run in in class repo
        run: echo No bomb to run in class repo

  grading-for-student:
    if: github.repository_owner != 'cu-csci-2400-computer-systems'
    runs-on: [self-hosted, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Install needed Ubuntu Packages 
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Check that you have a bomb file
        run: test -x bomb*/bomb
      - name: Check that you have a solution.txt file in your bomb directory
        run: make check-for-solution.txt
      - name: Check that the first 3 phases are correct
        run: make grade-first
      - name: Check that rest are correct
        run: make grade-rest
      - name: Check that the extra credit is correct
        run: make grade-extra
